#!/usr/bin/env python3
"""Generate include/iv/vk/colormap_lut.hpp (ADR-0014, D-0007; ADR-0036).

Bakes the committed cyclic phase colormaps into 256-entry RGBA8 LUTs, in mode order
skipping the analytic HSV map:

  layer 0 = twilight   (matplotlib 'twilight', cyclic, perceptually-uniform; ADR-0014)  -> mode 0
  layer 1 = infinity   (tools/colormaps/infinityRGBAcolormap.csv;  ADR-0036)            -> mode 2
  layer 2 = grayscale  (tools/colormaps/grayscaleRGBAcolormap.csv; ADR-0036)            -> mode 3

(colormapMode 1 is analytic HSV, so it has no baked layer.) Every layer is sampled at
texel centers ``(i + 0.5)/256`` so a linear + REPEAT 1D sampler reproduces the cyclic
map (entry 255 wraps smoothly back to entry 0). The custom maps arrive as 256 inclusive
samples over one cycle (row 0 == row 255 == the seam colour); they are treated as a
cyclic piecewise-linear map over ``u = k/255`` and resampled at the texel centers, so all
maps share one seam-uniform rule (ADR-0036).

Usage:
  tools/gen_colormap.py            # (re)write the header
  tools/gen_colormap.py --check    # exit 1 if the committed header is stale (CI gate)

Regenerate after changing a source map; do not hand-edit the output. Requires matplotlib.
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

N = 256
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "include" / "iv" / "vk" / "colormap_lut.hpp"
CSV_DIR = ROOT / "tools" / "colormaps"

# LUT layers in order (mode 1 = analytic HSV is not baked). Name -> source.
#   "twilight" is the matplotlib map; the rest are committed CSVs (<name>RGBAcolormap.csv).
LAYERS = ["twilight", "infinity", "grayscale"]


def bake_twilight() -> list[int]:
    cmap = matplotlib.colormaps["twilight"]
    out: list[int] = []
    for i in range(N):
        r, g, b, _a = cmap((i + 0.5) / N)
        out += [round(r * 255.0), round(g * 255.0), round(b * 255.0), 255]
    return out


def read_csv_rgb(name: str) -> list[tuple[float, float, float]]:
    path = CSV_DIR / f"{name}RGBAcolormap.csv"
    rows: list[tuple[float, float, float]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        parts = line.split(",")
        # Trailing '.' (e.g. "0.") and ints both parse as float.
        r, g, b = (float(parts[0]), float(parts[1]), float(parts[2]))
        rows.append((r, g, b))
    return rows


def bake_csv(name: str) -> list[int]:
    """Resample a cyclic map given as inclusive samples s[0..M-1] (s[0]==s[M-1]) at texel
    centers (i+0.5)/N. Samples sit at u_k = k/(M-1); the map is piecewise-linear in u."""
    s = read_csv_rgb(name)
    m = len(s)
    if m < 2:
        raise ValueError(f"{name}: need >= 2 rows, got {m}")
    out: list[int] = []
    for i in range(N):
        u = (i + 0.5) / N  # in (0, 1)
        x = u * (m - 1)
        k = int(x)  # 0 .. m-2 for u in (0,1)
        if k >= m - 1:
            k = m - 2
        f = x - k
        c0, c1 = s[k], s[k + 1]
        rgb = [c0[c] + (c1[c] - c0[c]) * f for c in range(3)]
        out += [round(rgb[0] * 255.0), round(rgb[1] * 255.0), round(rgb[2] * 255.0), 255]
    return out


def bake_layer(name: str) -> list[int]:
    return bake_twilight() if name == "twilight" else bake_csv(name)


def render_header() -> str:
    layers = [bake_layer(name) for name in LAYERS]
    count = len(LAYERS)
    lines = [
        "#ifndef IV_VK_COLORMAP_LUT_HPP",
        "#define IV_VK_COLORMAP_LUT_HPP",
        "",
        "// Generated by tools/gen_colormap.py (ADR-0014 / D-0007; ADR-0036). Cyclic phase",
        "// colormaps baked as 256 RGBA8 entries sampled at texel centers (i+0.5)/256 for a",
        "// linear + REPEAT 1D sampler. One layer per LUT map, in mode order skipping the",
        "// analytic HSV map (mode 1): layer 0 = twilight (mode 0), 1 = infinity (mode 2),",
        "// 2 = grayscale (mode 3). Regenerate; do NOT hand-edit.",
        "",
        "namespace iv::vk {",
        "",
        "inline constexpr unsigned int kColormapLutSize = 256;",
        f"inline constexpr unsigned int kColormapLutCount = {count}; // baked LUT layers "
        "(HSV mode 1 is analytic)",
        f"inline constexpr unsigned int kColormapModeCount = {count + 1}; // + analytic HSV (mode 1)",
        "",
        "// Layer -> map name (index matches kColormapLuts' first dimension).",
        "inline constexpr const char* kColormapLutNames[kColormapLutCount] = {",
        "    " + ", ".join(f'"{n}"' for n in LAYERS) + ",",
        "};",
        "",
        "inline constexpr unsigned char kColormapLuts[kColormapLutCount][256 * 4] = {",
    ]
    for name, data in zip(LAYERS, layers):
        lines.append(f"    {{ // {name}")
        for row in range(0, len(data), 32):
            chunk = data[row : row + 32]
            lines.append("        " + "".join(f"{v}," for v in chunk))
        lines.append("    },")
    lines += [
        "};",
        "",
        "} // namespace iv::vk",
        "",
        "#endif // IV_VK_COLORMAP_LUT_HPP",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    text = render_header()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is stale; run tools/gen_colormap.py", file=sys.stderr)
            return 1
        print(f"{OUT} is up to date")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT} ({len(LAYERS)} layers x {N} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
