#!/usr/bin/env python3
"""Generate include/iv/vk/colormap_lut.hpp (ADR-0014, D-0007).

The default phase colormap is matplotlib's cyclic, perceptually-uniform
``twilight`` map, baked into a 256-entry RGBA8 LUT. Entries are sampled at texel
centers ``(i + 0.5)/256`` so a linear + REPEAT 1D sampler reproduces the cyclic
map (entry 255 wraps smoothly back to entry 0).

Regenerate after changing the source map; do not hand-edit the output. Requires
matplotlib. A CI check can diff the regenerated header against the committed one
(like tools/regenerate_adr_index.py --check).
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

N = 256
OUT = Path(__file__).resolve().parent.parent / "include" / "iv" / "vk" / "colormap_lut.hpp"


def main() -> int:
    cmap = matplotlib.colormaps["twilight"]
    bytes_: list[int] = []
    for i in range(N):
        r, g, b, _a = cmap((i + 0.5) / N)
        bytes_ += [round(r * 255.0), round(g * 255.0), round(b * 255.0), 255]

    lines = [
        "#ifndef IV_VK_COLORMAP_LUT_HPP",
        "#define IV_VK_COLORMAP_LUT_HPP",
        "",
        "// Generated by tools/gen_colormap.py from matplotlib 'twilight' (cyclic,",
        "// perceptually-uniform; ADR-0014 / D-0007). 256 RGBA8 entries sampled at texel",
        "// centers (i+0.5)/256 for a linear + REPEAT 1D sampler. Regenerate; do not edit.",
        "",
        "namespace iv::vk {",
        "",
        "inline constexpr unsigned int kColormapLutSize = 256;",
        "",
        "inline constexpr unsigned char kTwilightLut[256 * 4] = {",
    ]
    # 8 RGBA entries (32 values) per line.
    for row in range(0, len(bytes_), 32):
        chunk = bytes_[row : row + 32]
        lines.append("    " + "".join(f"{v}," for v in chunk))
    lines += [
        "};",
        "",
        "} // namespace iv::vk",
        "",
        "#endif // IV_VK_COLORMAP_LUT_HPP",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(bytes_)} bytes, {N} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
