#!/usr/bin/env python3
"""Regenerate docs/adr/INDEX.md from the ADR files.

The ADR index is *mechanically generated* and MUST NOT be hand-edited
(DEV_PROCESS Section 1.4): hand-curation lets the index drift from the ADR
files. The ADR files are truth; this table is a convenience entry point.

Run this after adding an ADR or transitioning one's status. The script reads
every `NNNN-*.md` in docs/adr/ (excluding the template), extracts the title,
status, and supersession pointers, and rewrites INDEX.md.

Exit status:
  0  index written (and, with --check, already up to date)
  1  with --check, the on-disk index is stale (CI gate)
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ADR_DIR = Path(__file__).resolve().parent.parent / "docs" / "adr"
INDEX = ADR_DIR / "INDEX.md"
TEMPLATE = "0000-template.md"

ADR_FILE_RE = re.compile(r"^(\d{4})-.+\.md$")
TITLE_RE = re.compile(r"^#\s*ADR-(\d{4}):\s*(.+?)\s*$", re.MULTILINE)
STATUS_RE = re.compile(r"^-\s*\*\*Status:\*\*\s*(.+?)\s*$", re.MULTILINE)
SUPERSEDES_RE = re.compile(r"^-\s*\*\*Supersedes:\*\*\s*(.+?)\s*$", re.MULTILINE)
SUPERSEDED_BY_RE = re.compile(r"Superseded by ADR-(\d{4})", re.IGNORECASE)


def parse(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    title_m = TITLE_RE.search(text)
    status_m = STATUS_RE.search(text)
    sup_m = SUPERSEDES_RE.search(text)
    return {
        "num": path.name[:4],
        "file": path.name,
        "title": title_m.group(2) if title_m else "(missing title)",
        "status": status_m.group(1) if status_m else "(missing status)",
        "supersedes": sup_m.group(1).strip() if sup_m else "none",
    }


def supersession(entry: dict) -> str:
    parts = []
    by = SUPERSEDED_BY_RE.search(entry["status"])
    if by:
        parts.append(f"superseded by ADR-{by.group(1)}")
    if entry["supersedes"] and entry["supersedes"].lower() != "none":
        parts.append(f"supersedes {entry['supersedes']}")
    return "; ".join(parts) if parts else "—"


def render(adrs: list[dict]) -> str:
    lines = [
        "# ADR Index",
        "",
        "> Mechanically generated by `tools/regenerate_adr_index.py` "
        "(DEV_PROCESS §1.4). Do not hand-edit.",
        "> The ADR files are truth; this table is the entry point.",
        "",
    ]
    if not adrs:
        lines.append("_No ADRs yet._")
    else:
        lines.append("| ADR | Title | Status | Supersession |")
        lines.append("|-----|-------|--------|--------------|")
        for e in adrs:
            link = f"[ADR-{e['num']}]({e['file']})"
            lines.append(
                f"| {link} | {e['title']} | {e['status']} | {supersession(e)} |"
            )
    return "\n".join(lines) + "\n"


def collect() -> list[dict]:
    adrs = []
    for p in sorted(ADR_DIR.glob("*.md")):
        if p.name in (TEMPLATE, "INDEX.md"):
            continue
        if not ADR_FILE_RE.match(p.name):
            continue
        adrs.append(parse(p))
    return adrs


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if INDEX.md is stale instead of writing it",
    )
    args = ap.parse_args()

    content = render(collect())

    if args.check:
        current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        if current != content:
            print("docs/adr/INDEX.md is stale; run tools/regenerate_adr_index.py",
                  file=sys.stderr)
            return 1
        return 0

    INDEX.write_text(content, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(ADR_DIR.parent.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
